<?php

/**
 * Implements hook_init().
 */
function support_bar_init() {
  if (variable_get('support_bar_enabled', 0) == 1) {
    $support = array(
      'support_bar_phone_number' => variable_get('support_bar_phone_number', ''),
      'support_bar_filepath' => variable_get('support_bar_filepath', ''),
      'support_bar_url' => variable_get('support_bar_url', '/'),
    );

    $bar_html = theme('support_bar', $support);

    drupal_add_css(drupal_get_path('module', 'support_bar') . '/css/support_bar.css');
    drupal_add_js(array('support_bar' => array('support_bar_html' => $bar_html)), 'setting');
    drupal_add_js(drupal_get_path('module', 'support_bar') . '/js/support_bar.js', array('scope' => 'footer', 'weight' => 1000, 'preprocess' => TRUE));
  }
}

/**
 * Implements hook_permission().
 * @return array
 */
function support_bar_permission() {
  return array(
    'access support bar' => array(
      'title' => t('Access Support Bar'),
      'description' => t('User can use the support bar.'),
    )
  );
}

/**
 * Implements hook_menu().
 * @return array
 */
function support_bar_menu() {
  $items = array();

  $items['admin/config/system/support-bar'] = array(
    'title' => 'Support Bar',
    'description' => 'Configure settings for Support Bar.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('support_bar_admin_settings'),
    'access arguments' => array('access support bar'),
    'file' => 'support_bar.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 * @return array
 */
function support_bar_theme() {
  return array(
    'support_bar' => array(
      'template' => 'support_bar',
      'variables' => array('support' => NULL),
    ),
  );
}

/**
 * Implements hook_preprocess().
 * @param $vars
 */
function support_bar_preprocess_support_bar(&$vars) {

}