<?php

/**
 * Implements hook_init().
 */
function support_bar_init() {
  if (variable_get('support_bar_enabled', 0) == 1 && user_access('access support bar')) {
    $support = array(
      'phone_number' => variable_get('support_bar_phone_number', ''),
      'filepath' => variable_get('support_bar_filepath', ''),
      'url' => variable_get('support_bar_url', '/'),
    );

    $bar_html = theme('support_bar', $support);
    drupal_add_css(drupal_get_path('module', 'support_bar') . '/css/support_bar.css');
    drupal_add_js(array('support_bar' => array('support_bar_html' => $bar_html)), 'setting');
    drupal_add_js(drupal_get_path('module', 'support_bar') . '/js/support_bar.js', array('scope' => 'footer', 'weight' => 1000, 'preprocess' => TRUE));
  }
}

/**
 * Implements hook_permission().
 * @return array
 */
function support_bar_permission() {
  return array(
    'administer support bar' => array(
      'title' => t('Administer Support Bar'),
      'description' => t('User can configure support bar settings.'),
    ),
    'access support bar' => array(
      'title' => t('Access Support Bar'),
      'description' => t('User can use the support bar.'),
    )
  );
}

/**
 * Implements hook_menu().
 * @return array
 */
function support_bar_menu() {
  $items = array();

  $items['admin/config/system/support-bar'] = array(
    'title' => 'Support Bar',
    'description' => 'Configure settings for Support Bar.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('support_bar_admin_settings'),
    'access arguments' => array('administer support bar'),
    'file' => 'support_bar.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 * @return array
 */
function support_bar_theme() {
  return array(
    'support_bar' => array(
      'template' => 'support_bar',
      'variables' => array('support' => NULL),
    ),
  );
}

/**
 * Implements hook_preprocess().
 * @param $variables
 */
function support_bar_preprocess_support_bar(&$variables) {
  $variables['email'] = l('Contact Us', 'mailto:' . variable_get('site_mail', ''), array('absolute' => TRUE));
  $variables['logo'] = l(theme('image', array('path' => $variables['filepath'])), $variables['url'], array('html' => TRUE));
}